---
always_allow_html: true
params: 
  report_date: "2021-06-21"
  location_code: "DE"
  location_name: "Germany"
  restrict_weeks: 4
output:
  html_document:
    theme: yeti
    self_contained: true
    css: https://covid19forecasthub.eu/css/styles.css
title: "`r paste('European COVID-19 Forecast Hub Evaluation Report for', params$location_name)`"
date: "`r params$report_date`"
---

```{r setup, include=FALSE}
library(scoringutils)
library(ggplot2)
library(dplyr)
library(DT)
library(here)
library(knitr)
library(covidHubUtils)
library(lubridate)
knitr::opts_chunk$set(echo = FALSE, 
                      message = FALSE, 
                      warning = FALSE,
                      # stabilize fig.path to avoid invalidating cache for each country
                      fig.path = here("html", "report-country-files/"))

include_ranking <- TRUE
include_forecast_plot <- TRUE
include_avail_forecasts <- FALSE
include_ranks_over_time <- FALSE

include_countries <- include_forecast_plot || 
  include_forecast_plot || 
  include_avail_forecasts || 
  include_ranks_over_time

report_date <- lubridate::ymd(params$report_date)
restrict_weeks <- params$restrict_weeks
facetting_var <- rlang::quo(model)

source(here("code", "config_utils", "get_hub_config.R"))
data_types <- get_hub_config("target_variables")

options(knitr.duplicate.label = "allow")
```

<!--- Chunk to load forecast and truth data and consolidate it in a single df called data. Usually called as the first chunk. This step is cached so make sure to delete the cached files if necessary when testing. -->
```{r load-data, child = "../rmdchunks/load-data.Rmd"}
```

<!--- Chunk to filter data to keep only the relevant locations. Is is separated from the global data loading step
so that we can cache the loading step.. -->
```{r filter-data, child = "../rmdchunks/filter-country-data.Rmd"}
```

<!--- Define targets and horizons -->
```{r define-targets-horizons, child = "../rmdchunks/define-targets-horizons.Rmd"}
```

<!--- Visualisation of forecasts (cases or deaths across time) for multiple
forecasting dates. --->
```{r forecast-vis, child = if (include_forecast_plot) "../rmdchunks/plot-forecasts.Rmd"}
```

<!--- Table comparing the performance of each model. The table is followed by
an explanation text detailing the meaning of each column/index. --->
```{r model-ranking, child = if (include_ranking) "../rmdchunks/ranking.Rmd", results = 'asis'}
```

<!--- Forecasts diagnostics (WIS, overprediction, underprediction and sharpness)
over time. --->
```{r scores-time, child = "../rmdchunks/scores-and-truth-time.Rmd"}
```

<!--- Footer about GitHub repository and where to find data for individual 
models --->
```{r footer, child = "../rmdchunks/evaluation-footer.Rmd"}
```





