---
title: "Weekly report"
author: "European forecasting hub"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup}
source(here::here("template", "report-inputs.R"))
```

We collect, visualise, and synthesise forecasts of Covid-19 cases and deaths across `r location_count` European countries.

This week, we collected forecasts from `r team_count` teams, each contributing a short-term forecast of new Covid-19 deaths or cases for at least one country. We combined these forecasts on `r format(forecast_date, "%d %B %Y")`.

### Trends in the latest forecasts
### Overall situation

Over the next four weeks, forecasters largely expect `r trends$major` changes to cases and deaths from Covid-19, with this trend forecast in `r trends[(trends$major)]` countries across Europe are forecast to report `r trends$major`.

Reports of cases and/or deaths per 100,000 population are expected to increase in `r trends["increasing"]` countries, largely across `r increasing_region`. `r country$case$incr$location_name[1]` is likely to see the greatest increase in cases per 100,000 population, expected to increase from `r country$case$incr$latest_100k[1]` per 100,000 to approximately `r country$case$incr$forecast_100k_0.5[1]` (in the range of `r country$case$incr$forecast_100k_0.25[1]` - `r country$case$incr$forecast_100k_0.75[1]`).

#### Deaths from Covid-19

Forecasters expect that ... will see the most new deaths over the next week. 

On average across Europe, forecasters expect that the number of newly reported Covid-19 deaths will likely ... over the next 4 weeks, with ... to ... new deaths likely reported in the week ending ... . 

These forecasts predict that over the next 4 weeks, the number of newly reported deaths per week will likely ... in ... countries, which are indicated in the forecast plots below. Meanwhile, newly reported deaths will likely ... in ... countries. Trends in numbers of future reported deaths are uncertain or predicted to remain stable in the other states and territories.
