---
title: "European data status"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(gh)
library(dplyr)
library(stringr)
library(here)
library(readr)
library(tibble)
library(countrycode)
```

#### Potential issues in the JHU dataset 

As at `r Sys.time()`

```{r issues, echo=FALSE, message=FALSE}

# Get locations
locations <- pull(readr::read_csv("https://raw.githubusercontent.com/epiforecasts/covid19-forecast-hub-europe/main/data-locations/locations_eu.csv"),
                         location)
countries <- countrycode::codelist %>%
  filter(iso2c %in% locations) %>%
  select(fips, country.name.en) %>%
  mutate(fips = str_to_lower(fips),
         country.name.en = str_to_lower(country.name.en))
country_ch <- c(countries$fips, countries$country.name.en)
country_ch <- country_ch[!country_ch %in% c("be", "no")]
country_ch <- paste0("\\b", country_ch, "\\b", collapse = "|")

# Get issues in last six weeks
issues <- gh("GET /repos/CSSEGISandData/COVID-19/issues", 
             username = "CSSEGISandData",
             state = "open",
             since = Sys.Date() - (7*8), 
             sort = "updated", 
             per_page = 100)
# Get matching issues
issues <- tibble::tibble("issue" = vapply(issues, "[[", "", "title"),
                         "message" = vapply(issues, "[[", "", "body"),
                         "url" = vapply(issues, "[[", "", "html_url"),
                         "created" = as.Date(vapply(issues, "[[", "", "created_at")),
                         "updated" = as.Date(vapply(issues, "[[", "", "updated_at"))) %>%
  mutate(issue = str_to_lower(issue),
         message = str_replace_all(message, "\\r\\n", " "),
         message = str_c(str_sub(message, start = 1, end = 50), "..."),
         country = str_extract(issue, country_ch)) %>%
  filter(str_detect(issue, country_ch) &
         str_detect(url, "issues")) %>%
  select(country, created, updated, issue, message, url) %>%
  group_by(country) %>%
  arrange(desc(updated))

knitr::kable(issues, escape = FALSE)

```
Open issues updated over the last eight weeks: from [JHU CSSEGISandData Github](https://github.com/CSSEGISandData/COVID-19/)