#' @keywords internal
"_PACKAGE"

utils::globalVariables(
  c(
    "ae",
    "all_quantiles_all_horizons",
    "all_quantiles_present",
    "continuous_weeks",
    "designation",
    "forecast_date",
    "horizon",
    "included_in_ensemble",
    "inv_skill",
    "location",
    "model",
    "nall",
    "not_excluded_manually",
    "prediction",
    "present",
    "quantile",
    "relative_skill",
    "sum_inv_skill",
    "target",
    "target_end_date",
    "target_variable",
    "temporal_resolution",
    "true_value",
    "type",
    "value",
    "weight"
  )
)
