---
always_allow_html: true
params:
  report_date: "2021-06-21"
  subdir: ""
  plot_weeks: 1
  data_weeks: "10"
  model: "EuroCOVIDhub-ensemble"
output:
  html_document:
    theme: yeti
    self_contained: true
    css: https://covid19forecasthub.eu/css/styles.css
title: "`r paste0('European COVID-19 Forecast Hub Evaluation Report for ', params$model)`"
date: "`r params$report_date`"
---

```{r setup, include=FALSE}
library(scoringutils)
library(ggplot2)
library(dplyr)
library(tidyr)
library(DT)
library(knitr)
library(covidHubUtils)
library(lubridate)
library(here)
library(EuroForecastHub)
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE,
                      fig.path = here("html", "report-model-files/"))

include_calibration <- TRUE
include_forecast_plot <- TRUE

restrict_weeks <- params$restrict_weeks

report_date <- params$report_date
model <- params$model
facetting_var <- rlang::quo(location_name)

## first model (ensemble) always in blue, others in red
palette <- RColorBrewer::brewer.pal(3, "Set1")[2:1]
```

<!--- Fetch various values from the config file --->
```{r get-config-vars, child = "../rmdchunks/get-config-vars.Rmd"}
```

<!--- Chunk to load forecast and truth data and consolidate it in a single df called data. Usually called as the first chunk. This step is cached so make sure to delete the cached files if necessary when testing. -->
```{r load-data, child = "../rmdchunks/load-data.Rmd"}
```

<!--- Load forecast scores -->
```{r load-scores, child = "../rmdchunks/load-scores.Rmd"}
```

<!--- Chunk to filter data and scores to keep only the relevant locations, horizons and target varaibles. Is is separated from the global scoring step
so that we can cache the loading and scoring step.. -->
```{r filter-forecasts, child = "../rmdchunks/filter-forecasts.Rmd"}
```

<!--- Visualise the latest forecasts. -->
```{r plot-forecasts, child = "../rmdchunks/plot-forecasts.Rmd"}
```

<!-- Focus on 10 week scores. -->
```{r limit-scores, echo = FALSE}
table <- table %>%
  filter(weeks_included == params$data_weeks)
```

<!-- Visualisation of model scores. -->
```{r model-scores, child = "../rmdchunks/model-scores.Rmd"}
```

<!--- 
- Table with coverage by horizon for this week
- Plot of coverage by target and horizon over time
- PIT histograms
--->
```{r forecast-calibration, child = "../rmdchunks/forecast-calibration.Rmd"}
```
