---
params: 
  report_date: "2021-06-21"
  restrict_weeks: 4
  model: "EuroCOVIDhub-ensemble"
  location_name: NULL
always_allow_html: true
output:
  html_document:
    theme: yeti
    self_contained: true
    css: https://covid19forecasthub.eu/css/styles.css
title: "European COVID-19 Forecast Hub Ensemble Report"
date: "`r params$report_date`"
---

```{r setup, include=FALSE}
library(ggplot2)
library(dplyr)
library(DT)
library(knitr)
library(covidHubUtils)
library(lubridate)
library(here)
library(readr)
library(EuroForecastHub)
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)

include_calibration <- TRUE
include_forecast_plot <- TRUE

restrict_weeks <- params$restrict_weeks

report_date <- params$report_date
model <- params$model
facetting_var <- rlang::quo(location_name)
```

<!--- Fetch various values from the config file --->
```{r get-config-vars, child = "../rmdchunks/get-config-vars.Rmd"}
```

<!--- Chunk to load forecast and truth data and consolidate it in a single df called data. Usually called as the first chunk. This step is cached so make sure to delete the cached files if necessary when testing. -->
```{r load-data, child = "../rmdchunks/load-data.Rmd"}
```

<!-- Visualisation of forecasts (cases or deaths across time) for multiple
forecasting dates. -->
```{r forecast-vis, child = if (include_forecast_plot) "../rmdchunks/plot-forecasts.Rmd"}
```

<!--- 
- Table with coverage by horizon for this week
- Plot of coverage by target and horizon over time
- PIT histograms
--->
```{r forecast-calibration, child = "../rmdchunks/forecast-calibration.Rmd"}
```
