```{r wis_time_prep, results = 'asis', fig.width = 8.5, fig.asp = fa}
## show 10 weeks score
df <- scores %>%
  filter(target_end_date > max(target_end_date) - weeks(10),
         target_variable == target_variables[variable],
         horizon == this_horizon)

model_df <- df %>%
  filter(model == params$model)

if (all(is.na(model_df$wis))) {
  cat("Skill is shown as weighted interval score",
      "is not calculated as the 23 quantile levels required are not being",
      "provided by the model.")
  df <- df %>%
    rename(skill = aem)
  model_df <- model_df %>%
    rename(skill = aem)
} else {
  cat("Skill is shown as weighted interval score.")
  df <- df %>%
    rename(skill = wis)
  model_df <- model_df %>%
    rename(skill = wis)
}

cat("\n")

df <- df %>%
  filter(grepl("hub-(baseline|ensemble)", model)) %>%
  bind_rows(model_df) %>%
  filter(location %in% unique(model_df$location))

nb_facets <- dplyr::n_distinct(df$location)
n_cols <- 3
n_rows <- (nb_facets - 1) %/% n_cols + 1
fa <- ifelse(nb_facets > 0, n_rows / n_cols, 1)
reduce_size <- max(ifelse(nb_facets >= n_cols, 1, nb_facets / n_cols), 0.5)
fw <- 8.5 * reduce_size
ow <- paste0(reduce_size * 100, "%")
```

```{r wis_time, results = 'asis', fig.width = fw, fig.asp = fa, out.width = ow}
if (nrow(model_df) > 0) {
  p <- ggplot(df, aes(x = target_end_date, y = skill, colour = model)) +
    scale_colour_manual("", values = palette) +
    facet_wrap(~ location_name, scales = "free_y", ncol = n_cols) +
    scale_y_continuous("Skill", labels = scales::comma) +
    xlab("Target date") +
    geom_line() +
    geom_point() +
    theme_minimal() +
    theme(legend.position = "top")
  if (reduce_size < 1) {
    p <- p + guides(colour = guide_legend(nrow=2))
  }
  print(p)
} else {
  cat("Plots are only created for models that were used for forecasts in each of the last 4 weeks, excluding periods during which there were anomalies in the data. At the moment the model does not fulfills that criterion." )
}
```
