---
title: Hospitalisation data comparison
author: Sebastian Funk & Kath Sherratt
date: 15 December, 2022
output: ioslides_presentation
---

```{r setup, include = FALSE}
library("readr")
library("dplyr")
library("here")
library("stringr")
library("lubridate")
library("ggplot2")
```

```{r functions, include = FALSE}
plot_hosp <- function(df, weekday = 7) {
  plot_data <- df |>
    filter(wday(download_date) == weekday)
  min_max_date <- plot_data |>
    group_by(download_date) |>
    summarise(max_date = max(date)) |>
    summarise(min_max_date = min(max_date)) |>
    pull(min_max_date)
  start_date <- min_max_date - 4 * 7
  plot_data <- plot_data |>
    filter(date >= start_date)
  p <- ggplot(plot_data,
         aes(
           x = date,
           y = value,
           colour = as.factor(download_date),
           group = as.factor(download_date))) +
    scale_colour_brewer("", palette = "Dark2") +
    geom_line() +
    theme_bw() +
    xlab("") +
    ylab("Hospitalisations") +
    facet_wrap(~ location_name, scales = "free_y") +
    theme(legend.position = "top")
  return(list(plot = p, data = plot_data))
}

coverage_table <- function(df, weekday = 7) {
  table_data <- df |>
    group_by(download_date) |>
    summarise(n = n_distinct(location_name))
  return(table_data)
}
```

```{r load_data, include = FALSE}
file_types <- c("official", "scraped", "non-eu")
ecdc_data <- lapply(file_types, function(x) {
  ecdc_files <- list.files(
    path = here::here("data-truth", "ECDC", "raw"),
    pattern = paste0(x, "_202[0-9]-[0-9]{2}-[0-9]{2}.csv"),
    full.names = TRUE
  )
  ecdc_file_dates <- sub(
    "^.*(202[0-9]-[0-9]{2}-[0-9]{2}).csv$", "\\1", ecdc_files
  )
  type_data <- lapply(ecdc_files, read_csv, show_col_types = FALSE)
  names(type_data) <- ecdc_file_dates
  type_data <- bind_rows(type_data, .id = "download_date") |>
    mutate(download_date = as.Date(download_date))
  if ("indicator" %in% colnames(type_data)) {
   type_data <- type_data |>
    filter(
      is.na(indicator) |
      indicator %in%
        c("Weekly new hospital admissions per 100k", "New_Hospitalised")
    )
  }
  return(type_data)
})
names(ecdc_data) <- file_types

owid_files <- list.files(
    path = here::here("data-truth", "OWID"),
    pattern = paste0("202[0-9]-[0-9]{2}-[0-9]{2}.csv"),
    full.names = TRUE
)
owid_file_dates <- sub(
  "^.*(202[0-9]-[0-9]{2}-[0-9]{2}).csv$", "\\1", owid_files
)
owid_data <- lapply(owid_files, read_csv, show_col_types = FALSE)
names(owid_data) <- owid_file_dates
owid_data <- bind_rows(owid_data, .id = "download_date") |>
  mutate(download_date = as.Date(download_date))
```

## ECDC "official"

```{r ecdc_official, echo = FALSE}
pheo <- plot_hosp(ecdc_data[["official"]])
suppressWarnings(print(pheo$plot))
```

## ECDC "official": coverage

```{r ecdc_official_coverage, echo = FALSE}
coverage_table(pheo$data)
```

## ECDC "scraped": plots

```{r ecdc_scraped, echo = FALSE}
phes <- plot_hosp(ecdc_data[["scraped"]])
print(phes$plot)
```

## ECDC "scraped": coverage

```{r ecdc_scraped_coverage, echo = FALSE}
coverage_table(phes$data)
```

## Our World in Data: plots

```{r owid, echo = FALSE}
phowid <- plot_hosp(owid_data)
print(phowid$plot)
```

## Our World in Data: coverage

```{r owid_coverage, echo = FALSE}
coverage_table(phowid$data)
```
